### ISSUE TITLE
wrong example-conf/fcdecode.conf

### ISSUE THREAD

**Issue by jh4xsy** [funcube-dev/docker#2]
Please remove  connectaddress line. 

I know NO connectaddress line in REAME.md, but
I used this example and I got many errors.(192.168.0.XXX is my local DNS)
```
Failed to connect dial tcp: lookup warehouseserver on 192.168.0.XXX:53: no such host
```
After I removed that line, I was able to submit packets to warehouse.

**Comment by funcube-lead-dev** [comment]
Please can you give a little more background detail, as there will not be one configuration that suits all scenarios, perhaps there needs to be multiple examples?
What hardware are you running it on, docker versions, what steps did you take to build/run the containers.
Cheers,
D.

**Comment by jh4xsy** [comment]
Hi D.

I'm running this on Pi2B.

```
pi@pisdr:~ $ uname -a
Linux pisdr 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
pi@pisdr:~ $ docker --version
Docker version 19.03.11, build 42e35e6
```

I made container from 3 steps
```
% git clone https://github.com/funcube-dev/docker.git
% cd docker
% sh build.sh
```

To run container as interactive mode, I cut&paste from README.md to script.sh
When I included  connectaddress line, I see connectaddress bound to warehousseserver.
But warehouseserver is not in DNS or hosts.  

```
% sh script.sh
Using path: /home/pi
2020/06/21 04:53:57 Using Config:
...
2020/06/21 04:53:57 Opening command listen socket...
2020/06/21 04:53:57 Listening for commands on socket: 127.0.0.1:64519
2020/06/21 04:53:57 Opening listen socket...
2020/06/21 04:53:57 Listening on socket: 127.0.0.1:64518
2020/06/21 04:53:57 Ready to Send...
2020/06/21 04:53:57 Using Config:
audiodevicein -> -1
audiodeviceout -> -1
biast -> 0
bindaddress -> 127.0.0.1
commandport -> 64513
connectaddress -> warehouseserver ★
connectport -> 64518
exclude -> []
frequency -> 145900000
numdecoders -> 5
outdir -> 
```

**Comment by funcube-lead-dev** [comment]
Perfect thank you, that warehouseserver configuration line is needed when the two images fcdecode and fcwarehouse are run separately. However if using the fcrun image the connections are all internal to the container and configured with environment variables (overridden by command line and config file).
So in short, you’re right the example files should match the README, thanks for figuring it out...
Cheers, D.

**Comment by jh4xsy** [comment]
Thanks for your explanation. I Close this issue.
